BoxLayout:
    orientation: 'vertical'
    BoxLayout:
        orientation: 'horizontal'
        TextInput:
            id: input_miles
            size_hint_x: 0.8
            font_size: 48
            on_text: app.handle_calculate()
        BoxLayout:
            size_hint_x: 0.2
            orientation: 'vertical'
            Button:
                text: 'Up'
                on_press: app.handle_increment(1)
            Button:
                text: 'Down'
                on_press: app.handle_increment(-1)
#    Button:
#        text: 'Convert miles to km'
#        on_press: app.handle_calculate()
    Label:
        id: output_label
        font_size: 48
        text: '0.0'
        color: (1, 0.6, 0.6, 1)